/* eslint-disable @typescript-eslint/no-explicit-any */

import * as dotenv from "dotenv";
dotenv.config({ path: ".env.local" });

import { db } from "../index";
import {
  categories,
  brands,
  products,
  laptopSpecs,
  productImages,
} from "../schema";
import { eq } from "drizzle-orm";

import {
  getImagesFromFolder,
  groupImagesByProduct,
  sortProductImages,
} from "../utils/imagekit-helper";

const laptopDatabase: Record<string, any> = {
  // MACBOOK
  "macbook-pro-m4-16inch": {
    name: "MacBook Pro M4",
    category: "macbooks",
    brand: "apple",
    model: "MacBook Pro 14-inch M4",
    sku: "APPLE-MBP-M4-2024",
    warranty: "1 Year Apple Limited Warranty",
    releaseYear: 2024,
    basePrice: "187990.00",
    salePrice: "179990.00",
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    metaTitle: "MacBook Pro M4 - Buy Apple MacBook Pro 14-inch with M4 Chip",
    metaDescription:
      "Shop MacBook Pro M4 with 14.2-inch Liquid Retina XDR display, M4 Pro chip, 24GB RAM, and up to 24 hours battery life.",
    storageInfo: "512GB SSD",
    specs: {
      processorBrand: "Apple",
      processorModel: "M4 Pro",
      processorGeneration: "M4",
      processorCores: 12,
      processorThreads: 12,
      processorSpeed: "3.5GHz",
      processorBoostSpeed: "4.5GHz",
      ramSize: 24,
      ramType: "Unified Memory",
      storageInterface: "PCIe",
      additionalStorageSlots: 0,
      screenSize: "14.2",
      screenResolution: "3024x1964",
      screenType: "Liquid Retina XDR",
      refreshRate: 120,
      brightness: 1600,
      colorGamut: "100% DCI-P3",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "16-core GPU",
      weight: "1.55",
      dimensions: "312.6 x 221.2 x 15.5 mm",
      material: "Aluminum",
      color: "Space Black",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "72.4Wh",
      batteryLife: "Up to 24 hours",
      chargerWattage: 96,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.3",
      ethernet: false,
      usbPorts: "3x Thunderbolt 4",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "6-speaker system with Spatial Audio",
      microphone: "Studio-quality three-mic array",
      webcam: "12MP Center Stage",
      webcamPrivacyShutter: false,
      operatingSystem: "macOS Sequoia",
    },
  },

  // ULTRABOOKS
  "galaxy-book4-ultra-16-inch": {
    name: "Samsung Galaxy Book 4 Ultra 16",
    category: "ultrabooks",
    brand: "samsung",
    model: "Galaxy Book 4 Ultra",
    sku: "SAMSUNG-GB4U-16-2024",
    warranty: "1 Year Samsung Manufacturer Warranty",
    releaseYear: 2024,
    basePrice: "149999.00",
    salePrice: "139999.00",
    isNewArrival: true,
    isBestseller: false,
    isFeatured: true,
    metaTitle: "Samsung Galaxy Book 4 Ultra 16 - Premium Ultrabook",
    metaDescription:
      "Samsung Galaxy Book 4 Ultra with Intel Core Ultra 9, 32GB RAM, NVIDIA RTX 4050, and 16-inch AMOLED display.",
    storageInfo: "1TB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core Ultra 9 185H",
      processorGeneration: "14th Gen",
      processorCores: 16,
      processorThreads: 22,
      processorSpeed: "2.3GHz",
      processorBoostSpeed: "5.1GHz",
      ramSize: 32,
      ramType: "LPDDR5X",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 0,
      screenSize: "16.0",
      screenResolution: "2880x1800",
      screenType: "AMOLED",
      refreshRate: 120,
      brightness: 500,
      colorGamut: "100% DCI-P3",
      touchscreen: true,
      graphicsCard: "NVIDIA RTX 4050",
      graphicsMemory: 6,
      integratedGraphics: "Intel Arc",
      weight: "1.80",
      dimensions: "355 x 250 x 16.5 mm",
      material: "Aluminum",
      color: "Moonstone Gray",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "76Wh",
      batteryLife: "Up to 12 hours",
      chargerWattage: 100,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.3",
      ethernet: false,
      usbPorts: "2x USB-C Thunderbolt 4, 1x USB-A 3.2",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "Quad speakers with Dolby Atmos",
      microphone: "Dual-array microphone",
      webcam: "1080p FHD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Pro",
    },
  },

  "msi-creator-a16-ai+": {
    name: "MSI Creator A16 AI+",
    category: "ultrabooks",
    brand: "msi",
    model: "Creator A16 AI+",
    sku: "MSI-CA16-AI-2024",
    warranty: "2 Year MSI Manufacturer Warranty",
    releaseYear: 2024,
    basePrice: "139999.00",
    salePrice: null,
    isNewArrival: true,
    isBestseller: false,
    isFeatured: false,
    metaTitle: "MSI Creator A16 AI+ - Content Creation Powerhouse",
    metaDescription:
      "MSI Creator A16 AI+ with AMD Ryzen AI 9, 32GB RAM, RTX 4060, and 165Hz display for creators.",
    storageInfo: "1TB NVMe SSD",
    specs: {
      processorBrand: "AMD",
      processorModel: "Ryzen AI 9 HX 370",
      processorGeneration: "Ryzen AI",
      processorCores: 12,
      processorThreads: 24,
      processorSpeed: "2.0GHz",
      processorBoostSpeed: "5.1GHz",
      ramSize: 32,
      ramType: "DDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 1,
      screenSize: "16.0",
      screenResolution: "2560x1600",
      screenType: "IPS",
      refreshRate: 165,
      brightness: 400,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: "NVIDIA RTX 4060",
      graphicsMemory: 8,
      integratedGraphics: "AMD Radeon 890M",
      weight: "2.00",
      dimensions: "357 x 259 x 19.9 mm",
      material: "Aluminum",
      color: "Star Blue",
      backlitKeyboard: true,
      fingerprintReader: false,
      batteryCapacity: "90Wh",
      batteryLife: "Up to 10 hours",
      chargerWattage: 150,
      usbCCharging: true,
      wifi: "Wi-Fi 7",
      bluetooth: "5.4",
      ethernet: false,
      usbPorts: "2x USB-C, 2x USB-A 3.2",
      hdmiPort: true,
      displayPort: true,
      audioJack: true,
      sdCardReader: true,
      speakers: "2x 2W stereo speakers",
      microphone: "Dual-array microphone",
      webcam: "1080p IR",
      webcamPrivacyShutter: true,
      operatingSystem: "Windows 11 Pro",
    },
  },

  "lenovo-thinkbook-14s": {
    name: "Lenovo ThinkBook 14s",
    category: "ultrabooks",
    brand: "lenovo",
    model: "ThinkBook 14s Gen 5",
    sku: "LENOVO-TB14S-G5-2024",
    warranty: "1 Year Lenovo Onsite Warranty",
    releaseYear: 2024,
    basePrice: "89999.00",
    salePrice: "84999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Lenovo ThinkBook 14s - Business Ultrabook",
    metaDescription:
      "Lenovo ThinkBook 14s with Intel Core i7, 16GB RAM, and premium build for business professionals.",
    storageInfo: "512GB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i7-1355U",
      processorGeneration: "13th Gen",
      processorCores: 10,
      processorThreads: 12,
      processorSpeed: "1.7GHz",
      processorBoostSpeed: "5.0GHz",
      ramSize: 16,
      ramType: "LPDDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 0,
      screenSize: "14.0",
      screenResolution: "2240x1400",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 300,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel Iris Xe",
      weight: "1.40",
      dimensions: "312.2 x 218 x 16.9 mm",
      material: "Aluminum",
      color: "Storm Grey",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "56Wh",
      batteryLife: "Up to 12 hours",
      chargerWattage: 65,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.1",
      ethernet: false,
      usbPorts: "2x USB-C, 2x USB-A",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: false,
      speakers: "2x 2W stereo speakers",
      microphone: "Dual-array microphone",
      webcam: "1080p with privacy shutter",
      webcamPrivacyShutter: true,
      operatingSystem: "Windows 11 Pro",
    },
  },

  "hp-elitebook-g5": {
    name: "HP EliteBook G5",
    category: "ultrabooks",
    brand: "hp",
    model: "EliteBook 840 G5",
    sku: "HP-EB840-G5-2023",
    warranty: "3 Year HP Care Pack",
    releaseYear: 2023,
    basePrice: "109999.00",
    salePrice: "99999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "HP EliteBook G5 - Enterprise Business Laptop",
    metaDescription:
      "HP EliteBook G5 with Intel Core i7, Bang & Olufsen audio, and enterprise-grade security features.",
    storageInfo: "512GB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i7-1265U",
      processorGeneration: "12th Gen",
      processorCores: 10,
      processorThreads: 12,
      processorSpeed: "1.8GHz",
      processorBoostSpeed: "4.8GHz",
      ramSize: 16,
      ramType: "DDR4",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 0,
      screenSize: "14.0",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 400,
      colorGamut: "72% NTSC",
      touchscreen: true,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel Iris Xe",
      weight: "1.35",
      dimensions: "321 x 224 x 18.9 mm",
      material: "Aluminum",
      color: "Silver",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "53Wh",
      batteryLife: "Up to 14 hours",
      chargerWattage: 65,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.2",
      ethernet: false,
      usbPorts: "2x USB-C Thunderbolt 4, 2x USB-A",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "Bang & Olufsen stereo",
      microphone: "Dual-array microphone",
      webcam: "720p IR with privacy shutter",
      webcamPrivacyShutter: true,
      operatingSystem: "Windows 11 Pro",
    },
  },

  "lg-gram-16-inch": {
    name: "LG Gram 16 Inch",
    category: "ultrabooks",
    brand: "lg",
    model: "Gram 16 2024",
    sku: "LG-GRAM16-2024",
    warranty: "1 Year LG Manufacturer Warranty",
    releaseYear: 2024,
    basePrice: "119999.00",
    salePrice: null,
    isNewArrival: true,
    isBestseller: false,
    isFeatured: false,
    metaTitle: "LG Gram 16 Inch - Ultra-Lightweight Laptop",
    metaDescription:
      "LG Gram 16 weighing just 1.19kg with Intel Core i7, 16GB RAM, and up to 22 hours battery life.",
    storageInfo: "512GB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i7-1360P",
      processorGeneration: "13th Gen",
      processorCores: 12,
      processorThreads: 16,
      processorSpeed: "2.2GHz",
      processorBoostSpeed: "5.0GHz",
      ramSize: 16,
      ramType: "LPDDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 0,
      screenSize: "16.0",
      screenResolution: "2560x1600",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 350,
      colorGamut: "99% DCI-P3",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel Iris Xe",
      weight: "1.19",
      dimensions: "355.9 x 243.4 x 16.8 mm",
      material: "Magnesium alloy",
      color: "Black",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "80Wh",
      batteryLife: "Up to 22 hours",
      chargerWattage: 65,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.1",
      ethernet: false,
      usbPorts: "2x USB-C Thunderbolt 4, 2x USB-A",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "2x 2W stereo speakers",
      microphone: "Dual-array microphone",
      webcam: "1080p with IR",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  "asus-vivobbok-14": {
    name: "Asus Vivobook 14",
    category: "ultrabooks",
    brand: "asus",
    model: "Vivobook 14 X1404",
    sku: "ASUS-VB14-X1404-2024",
    warranty: "1 Year ASUS Onsite Warranty",
    releaseYear: 2024,
    basePrice: "54999.00",
    salePrice: "49999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Asus Vivobook 14 - Affordable Everyday Laptop",
    metaDescription:
      "Asus Vivobook 14 with Intel Core i5, 8GB RAM, and sleek design perfect for students and professionals.",
    storageInfo: "512GB SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i5-1235U",
      processorGeneration: "12th Gen",
      processorCores: 10,
      processorThreads: 12,
      processorSpeed: "1.3GHz",
      processorBoostSpeed: "4.4GHz",
      ramSize: 8,
      ramType: "DDR4",
      storageInterface: "PCIe Gen 3",
      additionalStorageSlots: 0,
      screenSize: "14.0",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 250,
      colorGamut: "45% NTSC",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel UHD Graphics",
      weight: "1.40",
      dimensions: "324.2 x 213.9 x 17.9 mm",
      material: "Plastic",
      color: "Transparent Silver",
      backlitKeyboard: false,
      fingerprintReader: false,
      batteryCapacity: "42Wh",
      batteryLife: "Up to 6 hours",
      chargerWattage: 45,
      usbCCharging: true,
      wifi: "Wi-Fi 6",
      bluetooth: "5.0",
      ethernet: false,
      usbPorts: "1x USB-C, 2x USB-A",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: false,
      speakers: "2x 2W stereo speakers",
      microphone: "Built-in microphone",
      webcam: "720p HD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  // GAMING LAPTOPS
  "acer-predator-21x": {
    name: "Acer Predator 21X",
    category: "gaming-laptops",
    brand: "acer",
    model: "Predator 21X",
    sku: "ACER-P21X-2024",
    warranty: "2 Year Acer Gaming Warranty",
    releaseYear: 2024,
    basePrice: "699999.00",
    salePrice: null,
    isNewArrival: false,
    isBestseller: false,
    isFeatured: true,
    metaTitle: "Acer Predator 21X - Extreme Gaming Beast",
    metaDescription:
      "Acer Predator 21X with 21-inch curved display, Intel Core i9, 64GB RAM, and NVIDIA RTX 4090.",
    storageInfo: "2TB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i9-13900HX",
      processorGeneration: "13th Gen",
      processorCores: 24,
      processorThreads: 32,
      processorSpeed: "2.2GHz",
      processorBoostSpeed: "5.4GHz",
      ramSize: 64,
      ramType: "DDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 2,
      screenSize: "21.0",
      screenResolution: "2560x1080",
      screenType: "IPS Curved",
      refreshRate: 120,
      brightness: 300,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: "NVIDIA RTX 4090",
      graphicsMemory: 16,
      integratedGraphics: null,
      weight: "8.50",
      dimensions: "500 x 400 x 45 mm",
      material: "Aluminum chassis",
      color: "Black",
      backlitKeyboard: true,
      fingerprintReader: false,
      batteryCapacity: "88Wh",
      batteryLife: "Up to 3 hours",
      chargerWattage: 330,
      usbCCharging: false,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.2",
      ethernet: true,
      usbPorts: "5x USB-A 3.2, 2x USB-C",
      hdmiPort: true,
      displayPort: true,
      audioJack: true,
      sdCardReader: true,
      speakers: "5x 2W speakers with subwoofer",
      microphone: "Dual-array microphone",
      webcam: "1080p HD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  "dell-g15": {
    name: "Dell G15",
    category: "gaming-laptops",
    brand: "dell",
    model: "G15 5530",
    sku: "DELL-G15-5530-2024",
    warranty: "1 Year Dell Premium Support",
    releaseYear: 2024,
    basePrice: "89999.00",
    salePrice: "84999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Dell G15 - Affordable Gaming Laptop",
    metaDescription:
      "Dell G15 with Intel Core i7, NVIDIA RTX 4060, 165Hz display, perfect for budget gaming.",
    storageInfo: "512GB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i7-13650HX",
      processorGeneration: "13th Gen",
      processorCores: 14,
      processorThreads: 20,
      processorSpeed: "2.6GHz",
      processorBoostSpeed: "4.9GHz",
      ramSize: 16,
      ramType: "DDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 1,
      screenSize: "15.6",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 165,
      brightness: 300,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: "NVIDIA RTX 4060",
      graphicsMemory: 8,
      integratedGraphics: "Intel UHD",
      weight: "2.65",
      dimensions: "357.3 x 272.1 x 26.9 mm",
      material: "Plastic",
      color: "Dark Shadow Grey",
      backlitKeyboard: true,
      fingerprintReader: false,
      batteryCapacity: "56Wh",
      batteryLife: "Up to 5 hours",
      chargerWattage: 240,
      usbCCharging: false,
      wifi: "Wi-Fi 6",
      bluetooth: "5.2",
      ethernet: true,
      usbPorts: "3x USB-A 3.2, 1x USB-C",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: false,
      speakers: "2x 2W stereo speakers",
      microphone: "Dual-array microphone",
      webcam: "720p HD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  "lenovo-legion": {
    name: "Lenovo Legion 5 Pro",
    category: "gaming-laptops",
    brand: "lenovo",
    model: "Legion 5 Pro",
    sku: "LENOVO-L5P-2024",
    warranty: "1 Year Lenovo Legion Ultimate Support",
    releaseYear: 2024,
    basePrice: "129999.00",
    salePrice: null,
    isNewArrival: true,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Lenovo Legion 5 Pro - Premium Gaming Laptop",
    metaDescription:
      "Lenovo Legion 5 Pro with AMD Ryzen 7, RTX 4070, and 165Hz display for serious gamers.",
    storageInfo: "1TB NVMe SSD",
    specs: {
      processorBrand: "AMD",
      processorModel: "Ryzen 7 7745HX",
      processorGeneration: "Ryzen 7000",
      processorCores: 8,
      processorThreads: 16,
      processorSpeed: "3.6GHz",
      processorBoostSpeed: "5.1GHz",
      ramSize: 16,
      ramType: "DDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 1,
      screenSize: "16.0",
      screenResolution: "2560x1600",
      screenType: "IPS",
      refreshRate: 165,
      brightness: 500,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: "NVIDIA RTX 4070",
      graphicsMemory: 8,
      integratedGraphics: "AMD Radeon",
      weight: "2.50",
      dimensions: "356 x 264 x 23 mm",
      material: "Aluminum",
      color: "Storm Grey",
      backlitKeyboard: true,
      fingerprintReader: false,
      batteryCapacity: "80Wh",
      batteryLife: "Up to 6 hours",
      chargerWattage: 300,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.2",
      ethernet: true,
      usbPorts: "4x USB-A 3.2, 2x USB-C",
      hdmiPort: true,
      displayPort: true,
      audioJack: true,
      sdCardReader: false,
      speakers: "2x 2W stereo with Nahimic Audio",
      microphone: "Dual-array microphone",
      webcam: "1080p FHD",
      webcamPrivacyShutter: true,
      operatingSystem: "Windows 11 Home",
    },
  },

  "acer-helios-15-3d": {
    name: "Acer Predator Helios 15 3D",
    category: "gaming-laptops",
    brand: "acer",
    model: "Predator Helios 300 3D",
    sku: "ACER-PH15-3D-2024",
    warranty: "2 Year Acer Gaming Warranty",
    releaseYear: 2024,
    basePrice: "169999.00",
    salePrice: "159999.00",
    isNewArrival: true,
    isBestseller: false,
    isFeatured: true,
    metaTitle: "Acer Predator Helios 15 3D - Gaming with 3D Display",
    metaDescription:
      "Acer Predator Helios 15 3D with Intel Core i9, RTX 4070, and revolutionary 3D display technology.",
    storageInfo: "1TB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i9-13900HX",
      processorGeneration: "13th Gen",
      processorCores: 24,
      processorThreads: 32,
      processorSpeed: "2.2GHz",
      processorBoostSpeed: "5.4GHz",
      ramSize: 32,
      ramType: "DDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 1,
      screenSize: "15.6",
      screenResolution: "1920x1080",
      screenType: "3D IPS",
      refreshRate: 165,
      brightness: 300,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: "NVIDIA RTX 4070",
      graphicsMemory: 8,
      integratedGraphics: null,
      weight: "2.70",
      dimensions: "363 x 262 x 28 mm",
      material: "Plastic with metal lid",
      color: "Abyssal Black",
      backlitKeyboard: true,
      fingerprintReader: false,
      batteryCapacity: "90Wh",
      batteryLife: "Up to 5 hours",
      chargerWattage: 330,
      usbCCharging: false,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.2",
      ethernet: true,
      usbPorts: "3x USB-A 3.2, 2x USB-C Thunderbolt 4",
      hdmiPort: true,
      displayPort: true,
      audioJack: true,
      sdCardReader: false,
      speakers: "DTS:X Ultra audio",
      microphone: "Dual-array microphone",
      webcam: "1080p with temporal noise reduction",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  "dell-alienware-gaming": {
    name: "Dell Alienware M16",
    category: "gaming-laptops",
    brand: "dell",
    model: "Alienware M16 R2",
    sku: "DELL-AW-M16-R2-2024",
    warranty: "2 Year Dell Premium Support Plus",
    releaseYear: 2024,
    basePrice: "249999.00",
    salePrice: "239999.00",
    isNewArrival: true,
    isBestseller: true,
    isFeatured: true,
    metaTitle: "Dell Alienware M16 - Premium Gaming Laptop",
    metaDescription:
      "Dell Alienware M16 with Intel Core i9, NVIDIA RTX 4080, 240Hz display, and AlienFX RGB lighting.",
    storageInfo: "2TB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i9-13900HX",
      processorGeneration: "13th Gen",
      processorCores: 24,
      processorThreads: 32,
      processorSpeed: "2.2GHz",
      processorBoostSpeed: "5.4GHz",
      ramSize: 32,
      ramType: "DDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 1,
      screenSize: "16.0",
      screenResolution: "2560x1600",
      screenType: "IPS",
      refreshRate: 240,
      brightness: 500,
      colorGamut: "100% DCI-P3",
      touchscreen: false,
      graphicsCard: "NVIDIA RTX 4080",
      graphicsMemory: 12,
      integratedGraphics: null,
      weight: "3.00",
      dimensions: "367.3 x 298.8 x 24.8 mm",
      material: "Aluminum chassis",
      color: "Dark Metallic Moon",
      backlitKeyboard: true,
      fingerprintReader: false,
      batteryCapacity: "90Wh",
      batteryLife: "Up to 6 hours",
      chargerWattage: 330,
      usbCCharging: false,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.3",
      ethernet: true,
      usbPorts: "3x USB-A 3.2, 2x USB-C Thunderbolt 4",
      hdmiPort: true,
      displayPort: true,
      audioJack: true,
      sdCardReader: true,
      speakers: "2x 2W stereo with Dolby Atmos",
      microphone: "Dual-array microphone",
      webcam: "1080p FHD with IR",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  "lenovo-loq-15-irh8": {
    name: "Lenovo Legion H15 IRH8",
    category: "gaming-laptops",
    brand: "lenovo",
    model: "Legion H15 IRH8",
    sku: "LENOVO-LH15-IRH8-2024",
    warranty: "1 Year Lenovo Legion Ultimate Support",
    releaseYear: 2024,
    basePrice: "94999.00",
    salePrice: "89999.00",
    isNewArrival: true,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Lenovo Legion H15 IRH8 - Mid-Range Gaming",
    metaDescription:
      "Lenovo Legion H15 with Intel Core i7, RTX 4050, and 144Hz display for smooth gaming.",
    storageInfo: "512GB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i7-13650HX",
      processorGeneration: "13th Gen",
      processorCores: 14,
      processorThreads: 20,
      processorSpeed: "2.6GHz",
      processorBoostSpeed: "4.9GHz",
      ramSize: 16,
      ramType: "DDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 1,
      screenSize: "15.6",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 144,
      brightness: 300,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: "NVIDIA RTX 4050",
      graphicsMemory: 6,
      integratedGraphics: "Intel UHD",
      weight: "2.40",
      dimensions: "359 x 264 x 23 mm",
      material: "Plastic",
      color: "Storm Grey",
      backlitKeyboard: true,
      fingerprintReader: false,
      batteryCapacity: "60Wh",
      batteryLife: "Up to 5 hours",
      chargerWattage: 170,
      usbCCharging: false,
      wifi: "Wi-Fi 6",
      bluetooth: "5.1",
      ethernet: true,
      usbPorts: "3x USB-A 3.2, 1x USB-C",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: false,
      speakers: "2x 2W stereo with Nahimic Audio",
      microphone: "Dual-array microphone",
      webcam: "720p HD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  // BUSINESS LAPTOPS
  "acer-a15-41m-slim": {
    name: "Acer Aspire A15-41M",
    category: "business-laptops",
    brand: "acer",
    model: "Aspire 3 A315-41M",
    sku: "ACER-A3-A15-41M-2023",
    warranty: "1 Year Acer International Warranty",
    releaseYear: 2023,
    basePrice: "39999.00",
    salePrice: "36999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Acer Aspire A15-41M - Budget Business Laptop",
    metaDescription:
      "Acer Aspire A15 with AMD Ryzen 5, 8GB RAM, and long battery life for everyday computing.",
    storageInfo: "512GB SSD",
    specs: {
      processorBrand: "AMD",
      processorModel: "Ryzen 5 5500U",
      processorGeneration: "Ryzen 5000",
      processorCores: 6,
      processorThreads: 12,
      processorSpeed: "2.1GHz",
      processorBoostSpeed: "4.0GHz",
      ramSize: 8,
      ramType: "DDR4",
      storageInterface: "PCIe Gen 3",
      additionalStorageSlots: 0,
      screenSize: "15.6",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 250,
      colorGamut: "45% NTSC",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "AMD Radeon Graphics",
      weight: "1.80",
      dimensions: "363.4 x 238.5 x 17.9 mm",
      material: "Plastic",
      color: "Silver",
      backlitKeyboard: false,
      fingerprintReader: false,
      batteryCapacity: "48Wh",
      batteryLife: "Up to 7 hours",
      chargerWattage: 45,
      usbCCharging: true,
      wifi: "Wi-Fi 6",
      bluetooth: "5.0",
      ethernet: true,
      usbPorts: "2x USB-A 3.2, 1x USB-C",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: false,
      speakers: "2x 2W stereo speakers",
      microphone: "Built-in microphone",
      webcam: "720p HD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  "dell-inspiron-15-3000": {
    name: "Dell Inspiron 15-3000",
    category: "business-laptops",
    brand: "dell",
    model: "Inspiron 15 3520",
    sku: "DELL-INS15-3520-2023",
    warranty: "1 Year Dell Onsite Warranty",
    releaseYear: 2023,
    basePrice: "44999.00",
    salePrice: "41999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Dell Inspiron 15-3000 - Reliable Everyday Laptop",
    metaDescription:
      "Dell Inspiron 15-3000 with Intel Core i5, 8GB RAM, perfect for students and home users.",
    storageInfo: "512GB SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i5-1135G7",
      processorGeneration: "11th Gen",
      processorCores: 4,
      processorThreads: 8,
      processorSpeed: "2.4GHz",
      processorBoostSpeed: "4.2GHz",
      ramSize: 8,
      ramType: "DDR4",
      storageInterface: "PCIe Gen 3",
      additionalStorageSlots: 0,
      screenSize: "15.6",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 220,
      colorGamut: "45% NTSC",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel Iris Xe",
      weight: "1.85",
      dimensions: "358.5 x 235.6 x 18.9 mm",
      material: "Plastic",
      color: "Carbon Black",
      backlitKeyboard: false,
      fingerprintReader: false,
      batteryCapacity: "42Wh",
      batteryLife: "Up to 6 hours",
      chargerWattage: 45,
      usbCCharging: false,
      wifi: "Wi-Fi 5",
      bluetooth: "5.0",
      ethernet: true,
      usbPorts: "2x USB-A 3.2, 1x USB-C",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "2x 2W stereo speakers",
      microphone: "Built-in microphone",
      webcam: "720p HD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Home",
    },
  },

  "lenovo-thinkpad-x1-carbon": {
    name: "Lenovo ThinkPad X1 Carbon",
    category: "business-laptops",
    brand: "lenovo",
    model: "ThinkPad X1 Carbon Gen 11",
    sku: "LENOVO-X1C-G11-2024",
    warranty: "3 Year Lenovo Premier Support",
    releaseYear: 2024,
    basePrice: "149999.00",
    salePrice: "144999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: true,
    metaTitle: "Lenovo ThinkPad X1 Carbon - Premium Business Laptop",
    metaDescription:
      "Lenovo ThinkPad X1 Carbon with Intel Core i7, 16GB RAM, carbon fiber build, and 16 hours battery.",
    storageInfo: "512GB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i7-1365U",
      processorGeneration: "13th Gen",
      processorCores: 10,
      processorThreads: 12,
      processorSpeed: "1.8GHz",
      processorBoostSpeed: "5.2GHz",
      ramSize: 16,
      ramType: "LPDDR5",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 0,
      screenSize: "14.0",
      screenResolution: "1920x1200",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 400,
      colorGamut: "100% sRGB",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel Iris Xe",
      weight: "1.12",
      dimensions: "315.6 x 222.5 x 14.95 mm",
      material: "Carbon fiber",
      color: "Black",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "57Wh",
      batteryLife: "Up to 16 hours",
      chargerWattage: 65,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.2",
      ethernet: false,
      usbPorts: "2x USB-A 3.2, 2x USB-C Thunderbolt 4",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: false,
      speakers: "2x 2W Dolby Atmos",
      microphone: "Quad-array microphone",
      webcam: "1080p IR with privacy shutter",
      webcamPrivacyShutter: true,
      operatingSystem: "Windows 11 Pro",
    },
  },

  "dell-vostro15-5510-i5": {
    name: "Dell Vostro 15-i5",
    category: "business-laptops",
    brand: "dell",
    model: "Vostro 15 3530",
    sku: "DELL-VOSTRO15-3530-2024",
    warranty: "1 Year Dell ProSupport",
    releaseYear: 2024,
    basePrice: "54999.00",
    salePrice: "51999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Dell Vostro 15-i5 - SMB Business Laptop",
    metaDescription:
      "Dell Vostro 15 with Intel Core i5, 8GB RAM, fingerprint reader for small business professionals.",
    storageInfo: "512GB SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i5-1235U",
      processorGeneration: "12th Gen",
      processorCores: 10,
      processorThreads: 12,
      processorSpeed: "1.3GHz",
      processorBoostSpeed: "4.4GHz",
      ramSize: 8,
      ramType: "DDR4",
      storageInterface: "PCIe Gen 3",
      additionalStorageSlots: 0,
      screenSize: "15.6",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 250,
      colorGamut: "45% NTSC",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel UHD Graphics",
      weight: "1.66",
      dimensions: "358.5 x 235.6 x 18.9 mm",
      material: "Plastic",
      color: "Titan Grey",
      backlitKeyboard: false,
      fingerprintReader: true,
      batteryCapacity: "42Wh",
      batteryLife: "Up to 8 hours",
      chargerWattage: 45,
      usbCCharging: true,
      wifi: "Wi-Fi 6",
      bluetooth: "5.1",
      ethernet: true,
      usbPorts: "2x USB-A 3.2, 1x USB-C",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "2x 2W stereo speakers",
      microphone: "Built-in microphone",
      webcam: "720p HD",
      webcamPrivacyShutter: false,
      operatingSystem: "Windows 11 Pro",
    },
  },

  "acer-travelmate-p4-11th-gen-2": {
    name: "Acer TravelMate P4 11th Gen",
    category: "business-laptops",
    brand: "acer",
    model: "TravelMate P4 TMP414",
    sku: "ACER-TMP414-11G-2023",
    warranty: "3 Year Acer Business Warranty",
    releaseYear: 2023,
    basePrice: "64999.00",
    salePrice: "61999.00",
    isNewArrival: false,
    isBestseller: false,
    isFeatured: false,
    metaTitle: "Acer TravelMate P4 - Durable Business Laptop",
    metaDescription:
      "Acer TravelMate P4 with Intel Core i5, military-grade durability, and enterprise security features.",
    storageInfo: "512GB SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i5-1135G7",
      processorGeneration: "11th Gen",
      processorCores: 4,
      processorThreads: 8,
      processorSpeed: "2.4GHz",
      processorBoostSpeed: "4.2GHz",
      ramSize: 8,
      ramType: "DDR4",
      storageInterface: "PCIe Gen 3",
      additionalStorageSlots: 0,
      screenSize: "14.0",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 300,
      colorGamut: "72% NTSC",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel Iris Xe",
      weight: "1.60",
      dimensions: "328 x 236 x 19.9 mm",
      material: "Magnesium-aluminum alloy",
      color: "Black",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "56Wh",
      batteryLife: "Up to 12 hours",
      chargerWattage: 65,
      usbCCharging: true,
      wifi: "Wi-Fi 6",
      bluetooth: "5.1",
      ethernet: true,
      usbPorts: "2x USB-A 3.2, 1x USB-C Thunderbolt 4",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "2x 2W stereo with DTS Audio",
      microphone: "Dual-array microphone",
      webcam: "720p HD with privacy shutter",
      webcamPrivacyShutter: true,
      operatingSystem: "Windows 11 Pro",
    },
  },

  "lenovo-thinkpad-e15-gen4": {
    name: "Lenovo ThinkPad E15 Gen 4",
    category: "business-laptops",
    brand: "lenovo",
    model: "ThinkPad E15 Gen 4",
    sku: "LENOVO-TE15-G4-2023",
    warranty: "1 Year Lenovo Onsite Warranty",
    releaseYear: 2023,
    basePrice: "69999.00",
    salePrice: "66999.00",
    isNewArrival: false,
    isBestseller: true,
    isFeatured: false,
    metaTitle: "Lenovo ThinkPad E15 Gen 4 - Affordable ThinkPad",
    metaDescription:
      "Lenovo ThinkPad E15 Gen 4 with Intel Core i7, 16GB RAM, legendary ThinkPad keyboard and reliability.",
    storageInfo: "512GB NVMe SSD",
    specs: {
      processorBrand: "Intel",
      processorModel: "Core i7-1255U",
      processorGeneration: "12th Gen",
      processorCores: 10,
      processorThreads: 12,
      processorSpeed: "1.7GHz",
      processorBoostSpeed: "4.7GHz",
      ramSize: 16,
      ramType: "DDR4",
      storageInterface: "PCIe Gen 4",
      additionalStorageSlots: 0,
      screenSize: "15.6",
      screenResolution: "1920x1080",
      screenType: "IPS",
      refreshRate: 60,
      brightness: 300,
      colorGamut: "45% NTSC",
      touchscreen: false,
      graphicsCard: null,
      graphicsMemory: null,
      integratedGraphics: "Intel Iris Xe",
      weight: "1.70",
      dimensions: "365 x 240 x 19.9 mm",
      material: "Plastic with metal top cover",
      color: "Black",
      backlitKeyboard: true,
      fingerprintReader: true,
      batteryCapacity: "57Wh",
      batteryLife: "Up to 10 hours",
      chargerWattage: 65,
      usbCCharging: true,
      wifi: "Wi-Fi 6E",
      bluetooth: "5.2",
      ethernet: true,
      usbPorts: "2x USB-A 3.2, 2x USB-C",
      hdmiPort: true,
      displayPort: false,
      audioJack: true,
      sdCardReader: true,
      speakers: "2x 2W Dolby Audio",
      microphone: "Dual-array microphone",
      webcam: "720p HD with privacy shutter",
      webcamPrivacyShutter: true,
      operatingSystem: "Windows 11 Pro",
    },
  },
};

const laptopFolders = {
  Macbook: "macbooks",
  "Gaming Laptops": "gaming-laptops",
  "Business Laptops": "business-laptops",
  Ultrabook: "ultrabooks",
};

export async function seedLaptops() {
  console.log("💻 Seeding ALL 19 laptops with complete specifications...\n");

  const allBrands = await db.select().from(brands);
  const brandMap = new Map(allBrands.map((b) => [b.name.toLowerCase(), b]));

  for (const [folderName, categorySlug] of Object.entries(laptopFolders)) {
    console.log(`📁 Processing ${folderName}...`);

    const category = await db.query.categories.findFirst({
      where: eq(categories.slug, categorySlug),
    });

    if (!category) {
      console.log(`  ⚠️  Category not found: ${categorySlug}`);
      continue;
    }

    try {
      const result = await getImagesFromFolder(folderName, 100);

      if (!result.success) {
        console.error(`  ❌ Error fetching images:`, result.error);
        continue;
      }

      const files = result.files;
      console.log(`  🖼️  Found ${files.length} images`);

      const groupedProducts = groupImagesByProduct(files);
      console.log(
        `  📦 Grouped into ${Object.keys(groupedProducts).length} products\n`
      );

      for (const [baseName, images] of Object.entries(groupedProducts)) {
        const imageList = sortProductImages(images as any[]);
        const mainImage = imageList[0];

        const laptopKey = Object.keys(laptopDatabase).find((key) => {
          const searchTerm = baseName.toLowerCase().replace(/[-_\s]/g, "");
          const keyTerm = key.replace(/[-_\s]/g, "");
          return searchTerm.includes(keyTerm) || keyTerm.includes(searchTerm);
        });

        if (!laptopKey) {
          console.log(`  ⚠️  No specs found for: ${baseName} (skipping)`);
          continue;
        }

        const laptopData = laptopDatabase[laptopKey];
        const brandId = brandMap.get(laptopData.brand)?.id || null;

        const [product] = await db
          .insert(products)
          .values({
            name: laptopData.name,
            slug: `${categorySlug}-${laptopKey}`,
            description: `${laptopData.name} featuring ${
              laptopData.specs.processorBrand
            } ${laptopData.specs.processorModel} processor with ${
              laptopData.specs.processorCores
            } cores, ${laptopData.specs.ramSize}GB ${
              laptopData.specs.ramType
            }, ${laptopData.storageInfo}, and ${laptopData.specs.screenSize}" ${
              laptopData.specs.screenType
            } display. ${
              laptopData.specs.graphicsCard
                ? `Equipped with ${laptopData.specs.graphicsCard} ${laptopData.specs.graphicsMemory}GB graphics.`
                : ""
            } ${laptopData.specs.batteryLife} battery life. Perfect for ${
              laptopData.category === "gaming-laptops"
                ? "gamers"
                : laptopData.category === "business-laptops"
                ? "business professionals"
                : laptopData.category === "macbooks"
                ? "creative professionals"
                : "everyday computing"
            }.`,
            shortDescription: `${laptopData.specs.processorModel}, ${laptopData.specs.ramSize}GB RAM, ${laptopData.specs.screenSize}" ${laptopData.specs.screenType}, ${laptopData.specs.batteryLife}`,
            categoryId: category.id,
            brandId,
            productType: "laptop",
            mainImagePath: mainImage.filePath.replace(/^\//, ""),
            basePrice: laptopData.basePrice,
            salePrice: laptopData.salePrice,
            model: laptopData.model,
            sku: laptopData.sku,
            warranty: laptopData.warranty,
            releaseYear: laptopData.releaseYear,
            isActive: true,
            isFeatured: laptopData.isFeatured,
            isNewArrival: laptopData.isNewArrival,
            isBestseller: laptopData.isBestseller,
            stockQuantity: 25,
            metaTitle: laptopData.metaTitle,
            metaDescription: laptopData.metaDescription,
            quickSpecs: {
              processor: `${laptopData.specs.processorBrand} ${laptopData.specs.processorModel}`,
              ram: `${laptopData.specs.ramSize}GB ${laptopData.specs.ramType}`,
              storage: laptopData.storageInfo,
              screen: `${laptopData.specs.screenSize}" ${laptopData.specs.screenResolution}`,
              graphics:
                laptopData.specs.graphicsCard ||
                laptopData.specs.integratedGraphics,
            },
          })
          .returning();

        await db.insert(laptopSpecs).values({
          productId: product?.id,
          processorBrand: laptopData.specs.processorBrand,
          processorModel: laptopData.specs.processorModel,
          processorGeneration: laptopData.specs.processorGeneration,
          processorCores: laptopData.specs.processorCores,
          processorThreads: laptopData.specs.processorThreads,
          processorSpeed: laptopData.specs.processorSpeed,
          processorBoostSpeed: laptopData.specs.processorBoostSpeed,
          ramSize: laptopData.specs.ramSize,
          ramType: laptopData.specs.ramType,
          storageInterface: laptopData.specs.storageInterface,
          additionalStorageSlots: laptopData.specs.additionalStorageSlots,
          screenSize: laptopData.specs.screenSize,
          screenResolution: laptopData.specs.screenResolution,
          screenType: laptopData.specs.screenType,
          refreshRate: laptopData.specs.refreshRate,
          brightness: laptopData.specs.brightness,
          colorGamut: laptopData.specs.colorGamut,
          touchscreen: laptopData.specs.touchscreen,
          graphicsCard: laptopData.specs.graphicsCard,
          graphicsMemory: laptopData.specs.graphicsMemory,
          integratedGraphics: laptopData.specs.integratedGraphics,
          weight: laptopData.specs.weight,
          dimensions: laptopData.specs.dimensions,
          material: laptopData.specs.material,
          color: laptopData.specs.color,
          backlitKeyboard: laptopData.specs.backlitKeyboard,
          fingerprintReader: laptopData.specs.fingerprintReader,
          batteryCapacity: laptopData.specs.batteryCapacity,
          batteryLife: laptopData.specs.batteryLife,
          chargerWattage: laptopData.specs.chargerWattage,
          usbCCharging: laptopData.specs.usbCCharging,
          wifi: laptopData.specs.wifi,
          bluetooth: laptopData.specs.bluetooth,
          ethernet: laptopData.specs.ethernet,
          usbPorts: laptopData.specs.usbPorts,
          hdmiPort: laptopData.specs.hdmiPort,
          displayPort: laptopData.specs.displayPort,
          audioJack: laptopData.specs.audioJack,
          sdCardReader: laptopData.specs.sdCardReader,
          speakers: laptopData.specs.speakers,
          microphone: laptopData.specs.microphone,
          webcam: laptopData.specs.webcam,
          webcamPrivacyShutter: laptopData.specs.webcamPrivacyShutter,
          operatingSystem: laptopData.specs.operatingSystem,
        });

        for (let i = 0; i < imageList.length; i++) {
          const file = imageList[i];

          let imageType = "general";
          if (file.name.match(/-(v1|v2)\.(jpg|jpeg|png|webp)$/i)) {
            imageType = file.name.match(/-v1\./i) ? "angle-1" : "angle-2";
          } else {
            imageType = "front";
          }

          await db.insert(productImages).values({
            productId: product?.id,
            imagePath: file.filePath.replace(/^\//, ""),
            imageKitFileId: file.fileId,
            altText: `${laptopData.name} - ${imageType}`,
            isMainImage: i === 0,
            displayOrder: i,
            width: file.width,
            height: file.height,
            imageType,
          });
        }

        console.log(`  ✅ ${laptopData.name} (${imageList.length} images)`);
      }
    } catch (error) {
      console.error(`  ❌ Error processing ${folderName}:`, error);
    }
  }

  console.log(
    "\n🎉 All 19 laptops seeded successfully with complete specifications!\n"
  );
}

if (require.main === module) {
  seedLaptops()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error("❌ Error:", error);
      process.exit(1);
    });
}
